version: "2"

services:
  web:
    build: .
    command: nodemon -L --exec "npm run startdebug" --watch src
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/src/config
      - /usr/src/app/dist
    ports:
      - "8000:8000"
      - "9229:9229"
    depends_on:
      - postgres
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=ramirez
      - PG_DATABASE=hc
      - PG_HOST=postgres
      - IMAGES_DIRECTORY= /usr/src/app/images
  postgres:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hc
      POSTGRES_PASSWORD: ramirez
    ports:
      - "5433:5432"
